export default {
  editor: {
    label: { en: 'Spread Member Navbar' },
    icon: 'menu',
    categories: ['navigation'],
  },
  properties: {
    logoUrl: {
      label: { en: 'Logo URL' },
      type: 'Text',
      bindable: true,
      defaultValue: 'https://vwkrrpxnbcqrdkuwhnau.supabase.co/storage/v1/object/public/Branding%20CDN/Logos/SpreadPrimaryLogo.png',
    },
    logoMarkUrl: {
      label: { en: 'Logo Mark URL (mobile)' },
      type: 'Text',
      bindable: true,
      defaultValue: 'https://vwkrrpxnbcqrdkuwhnau.supabase.co/storage/v1/object/public/Branding%20CDN/Logos/MarkSpreadLogo.png',
    },
    isAuthenticated: {
      label: { en: 'Is Authenticated' },
      type: 'OnOff',
      bindable: true,
      defaultValue: false,
    },
    userName: {
      label: { en: 'User Name' },
      type: 'Text',
      bindable: true,
      defaultValue: '',
    },
    userEmail: {
      label: { en: 'User Email' },
      type: 'Text',
      bindable: true,
      defaultValue: '',
    },
    userAvatarUrl: {
      label: { en: 'User Avatar URL' },
      type: 'Text',
      bindable: true,
      defaultValue: '',
    },
    userId: {
      label: { en: 'User ID' },
      type: 'Text',
      bindable: true,
      hidden: true,
      defaultValue: '',
    },
    supabaseUrl: {
      label: { en: 'Supabase URL' },
      type: 'Text',
      bindable: true,
      hidden: true,
      defaultValue: '',
    },
    supabaseAnonKey: {
      label: { en: 'Supabase Anon Key' },
      type: 'Text',
      bindable: true,
      hidden: true,
      defaultValue: '',
    },
    accessToken: {
      label: { en: 'Auth Token' },
      type: 'Text',
      bindable: true,
      hidden: true,
      defaultValue: '',
    },
    cartItemCount: {
      label: { en: 'Cart Item Count (fallback)' },
      type: 'Number',
      bindable: true,
      defaultValue: 0,
    },
    showAlertBanner: {
      label: { en: 'Show Alert Banner' },
      type: 'OnOff',
      bindable: true,
      defaultValue: true,
    },
    showNotificationBell: {
      label: { en: 'Show Notification Bell' },
      type: 'OnOff',
      bindable: true,
      defaultValue: true,
    },
    alertBannerMaxCount: {
      label: { en: 'Max Alert Banners' },
      type: 'Number',
      bindable: true,
      defaultValue: 2,
      options: { min: 1, max: 5 },
    },
    pollIntervalAlerts: {
      label: { en: 'Alerts Poll Interval (s)' },
      type: 'Number',
      bindable: true,
      defaultValue: 60,
      options: { min: 15, max: 300 },
    },
    pollIntervalCart: {
      label: { en: 'Cart Poll Interval (s)' },
      type: 'Number',
      bindable: true,
      defaultValue: 15,
      options: { min: 5, max: 120 },
    },
    hideBuiltinTopbarIcons: {
      label: { en: 'Hide Built-in Cart & User Icons' },
      type: 'OnOff',
      bindable: true,
      defaultValue: false,
    },
  },
  triggerEvents: [
    {
      name: 'nav:navigate',
      label: { en: 'On Navigate' },
      event: { path: '', label: '' },
    },
    {
      name: 'nav:logout',
      label: { en: 'On Logout' },
      event: {},
    },
    {
      name: 'nav:cart',
      label: { en: 'On Cart Click' },
      event: { itemCount: 0 },
    },
    {
      name: 'nav:have-your-say',
      label: { en: 'On Have Your Say Click' },
      event: {},
    },
    {
      name: 'nav:menu-toggle',
      label: { en: 'On Menu Toggle' },
      event: { isOpen: false },
    },
    {
      name: 'nav:user-menu-open',
      label: { en: 'On User Menu Open' },
      event: {},
    },
    {
      name: 'nav:notification-bell-clicked',
      label: { en: 'On Notification Bell Clicked' },
      event: { unreadCount: 0 },
    },
    {
      name: 'nav:alert-banner-dismissed',
      label: { en: 'On Alert Banner Dismissed' },
      event: { alertId: '', headline: '', severity: '' },
    },
    {
      name: 'nav:alert-notification-clicked',
      label: { en: 'On Alert Notification Clicked' },
      event: { alertId: '', headline: '', severity: '', status: '' },
    },
  ],
};
